n1 = int(input("coloque um numero: "))
n2 = int(input("coloque outro numero: "))
print("a soma é: ", n1 + n2)
print("a subtração é: ", n1 - n2)
print("a multiplicação é: ", n1 * n2)
print("a divisão é: ", n1 / n2)
print("o resto de divisão é: ", n1%n2)